app-config {
  name = "postg"
  db-connection-config {
    host = "localhost"
    port = 5432
    user = "neom"
    password = "neom11"
    max-connections = 4
    min-idle-connections = 4
  }
  server-connection-config {
    host = "0.0.0.0"
    port = 443
    key-store-file = "certs/keystore.p12"
    key-store-password = "hgt67Y3!l9"
  }
  backend-server-config {
    number-of-workers = 4
    bounded-queue-capacity = 32
  }
  mem-cache-config {
    director-mem-cache-config {
      capacity = 4
      cleanup-duration-in-millis = 120000
      cache-enabled = true
    }
    actor-mem-cache-config {
      capacity = 4
      cleanup-duration-in-millis = 120000
      cache-enabled = true
    }
    movie-mem-cache-config {
      capacity = 4
      cleanup-duration-in-millis = 120000
      cache-enabled = true
    }
  }
  auth-config {
    secret-key = "myTopSecretKey!"
    expiration-period-in-seconds = 1800
    jwt-encoding-algorithm = "HS256"
  }
}
