app-config {
  db-connection-config {
    max-connections = 64
    min-idle-connections = 32
  }
  backend-server-config {
    number-of-workers = 64
    bounded-queue-capacity = 512
  }
  mem-cache-config {
    director-mem-cache-config {
      capacity = 400
    }
    actor-mem-cache-config {
      capacity = 400
    }
    movie-mem-cache-config {
      capacity = 400
    }
  }
}
